### ISSUE TITLE
Run with A6000 GPU

### ISSUE THREAD

**Issue by tianzheng4** [microsoft/DPSDA#2]
Could I run the experiment with A6000 GPU? It seems that A6000 is not enough for the default settings (CIFAR10). Shall I reduce the batch size or use data parallelism? 

Many thanks in advance for your help!

**Comment by fjxmlzn** [comment]
Yes, A6000 should be fine. In fact, I have tested the code on A6000.

The code with improved diffusion APIs (used for CIFAR10) already supports data parallelism by default. It will spread the data across all available GPUs automatically.

You can try decreasing the batch size (e.g., https://github.com/microsoft/DPSDA/blob/79f0868b1a13769c1d16bba3a32f81502690e83a/scripts/main_improved_diffusion_cifar10_conditional.sh#L32) till the point that does not raise OOM error.
